# Generated by Django 4.0.4 on 2022-11-27 21:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=None, max_length=50), size=None)),
                ('img', models.ImageField(default=None, upload_to='images')),
                ('name', models.ImageField(default=None, upload_to='images')),
            ],
        ),
    ]
